#!/bin/bash

#Setting the hostname variable
varHostname=$HOSTNAME

#Setting the user name variable
varUsername=$USER

#Date showing
varTimeDate=$(date)

#Setting the version and name of the OS variable with piping in the cut command
varNameVersion=$(cat /etc/os-release | grep PRETTY_NAME= | awk -F = '{print $2}')

#Uptime variable using cut with delimiter option
varUptime=$(uptime | cut -d p -f2 | cut -d , -f1)

#CPU make and model variable using LSHW
varCpuMake=$(lshw | grep product: | sed -n '1p' | cut -d : -f2) 

# Total memory using the free command and awk to select the word
varRam=$(free -h | grep "Mem:" | awk '{print $2}')

#Disk entry - size then make and model
varDisks=$(df -h / | awk '{print $1,$4}')

#GPU display
varGPU=$(inxi -G | grep "Device" | awk '{print $1,$2,$3,$4,$5}')

#Host address
varHostIp=$(ip route get 1.1.1.1 | awk '{print $7}')

#Default gateway address
varGateway=$(ip route | grep default | awk '{print $3}')

#DNS Server showing
varDNS=$(resolvectl | grep "Current DNS Server: " | awk '{print $4}')

#List of users with awk NR option to remove first two line of the chosen collumn
varUser=$(w | awk 'NR > 2 {print $1}')

#Disk Free space
varDiskRem=$(df -h / | awk '{print $1,$4}')

#process count with word count command
varPS=$(ps -e | wc -l)

#Load average using awk -F command to set a custom field
varLoad=$(uptime | awk -F 'load average: ' '{print $2}')

#Listening ports
varLP=$(ss -ltu | grep LISTEN | awk '{print $4}')

#Firewall status
varFWS=$(sudo ufw status)


#Script Execution

cat << EOF


 
System Report for $varHostname generated by $varUsername, on $varTimeDate

System Information
------------------
OS: $varNameVersion
Uptime: $varUptime
CPU: $varCpuMake
RAM: $varRam
Disks:
$varDisks
Video:
$varGPU 
Host Address: $varHostIp
Gateway IP: $varGateway
DNS Server: $varDNS

System Status
-------------
Users Logged In: $varUser
Disk Space:
$varDiskRem
Process Count: $varPS
Load Averages: $varLoad
Listening Network Ports:
$varLP
UFW Status: $varFWS


EOF
