#!/bin/bash

#Setting the hostname variable
varHostname=$HOSTNAME

#Setting the user name variable
varUsername=$USER

#Date showing
varTimeDate=$(date)

#Setting the version and name of the OS variable with piping in the cut command
varNameVersion=$(cat /etc/os-release | grep PRETTY_NAME= | awk -F = '{print $2}')

#Uptime variable using cut with delimiter option
varUptime=$(uptime | cut -d p -f2 | cut -d , -f1)

#CPU make and model variable using LSHW
varCpuMake=$(lshw | grep product: | sed -n '1p' | cut -d : -f2) 

# Total memory using the free command and awk to select the word
varRam=$(free -h | grep "Mem:" | awk '{print $2}')

#Disk entry - size then make and model
varDiskSize=$(lsblk | grep "sda " | awk '{print $4}')
varDiskName=$(lsblk -o NAME,VENDOR | grep "sda " | awk '{print $1}')
varDiskMake=$(lsblk -o NAME,VENDOR | grep "sda " | awk '{print $2}')

#GPU display
varGPU=$(lspci | grep -i vga | cut -w -f5,6,7,8)

#Host address
varHostIp=$(ip route get 1.1.1.1 | awk '{print $7}')

#Default gateway address
varGateway=$(ip route | grep default | awk '{print $3}')

#DNS Server showing
varDNS=$(resolvectl | grep "Current DNS Server: " | awk '{print $4}')

#List of users with awk NR option to remove first two line of the chosen collumn
varUser=$(w | awk 'NR > 2 {print $1}')

#Disk Free space
varDiskRem=$(df -h / | awk '{print $1,$4}')

#process count with word count command
varPS=$(ps -e | wc -l)

#Load average using awk -F command to set a custom field
varLoad=$(uptime | awk -F 'load average: ' '{print $2}')

#Listening ports
varLP=$(ss -ltu | grep LISTEN | awk '{print $4}')

#Firewall status
varFWS=$(sudo ufw status)

echo 
echo System Report for $varHostname generated by $varUsername, on $varTimeDate
echo
echo System Information
echo ------------------
echo OS: $varNameVersion
echo Uptime: $varUptime
echo CPU: $varCpuMake
echo RAM: $varRam
echo Disks: Name:$varDiskName Make:$varDiskMake Size:$varDiskSize
echo Video: $varGPU 
echo Host Address: $varHostIp
echo Gateway IP: $varGateway
echo DNS Server: $varDNS
echo
echo System Status
echo -------------
echo Users Logged In: $varUser
echo Disk Space: $varDiskRem
echo Process Count: $varPS
echo Load Averages: $varLoad
echo Listening Network Ports: $varLP
echo UFW Status: $varFWS
